AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ACG-Lambda

  Sample SAM Template for ACG-Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8
    Environment:
      Variables:
        LOG_LEVEL: 10

Resources:
  AdventureGuruFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: adventure_guru/
      Handler: lambda_function.handler
      Runtime: python3.8
      Role: arn:aws:iam::363326780846:role/service-role/adventure-guru-role-48a8fxbg

